name: Artifact Test

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create file
        run: "date >> ~/artifact-test.txt"
      - name: Print Environment Details
        run: ls /home/runner
      - name: Publish release
        id: release
        uses: ncipollo/release-action@release/1.8.5
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: "blarg.txt,~/artifact-test.txt"
          body: This release was generated to test artifact uploading.
          name: Artifact Test Release
          replacesArtifacts: true
          tag: test-tag
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump Release Outputs
        env:
          RELEASE_OUTPUT: ${{ toJson(steps.release.outputs) }}
        run: echo "$RELEASE_OUTPUT"
