name: Artifact Test

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create file
        run: "date >> ~/artifact-test.txt"
      - name: Print Environment Details
        run: ls /home/runner
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "blarg.txt,~/artifact-test.txt"
          body: This release was generated to test artifact uploading.
          name: Artifact Test Release
          replacesArtifacts: true
          tag: test-tag
          token: ${{ secrets.GITHUB_TOKEN }}
