name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo GITHUB_REF
        run: echo $GITHUB_REF
      - name: Tar text folder
        run: tar -czf text.tar.gz text
      - name: Publish release
        id: release
        uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifactContentType: "raw"
          bodyFile: "body.md"
          discussionCategory: "Release"
          draft: false
          prerelease: false
          removeArtifacts: true
      - name: Dump Release Outputs
        env:
          RELEASE_OUTPUT: ${{ toJson(steps.release.outputs) }}
        run: echo "$RELEASE_OUTPUT"
