name: Tags

on: 
  push:
    branches:
    - refs/tags/*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo GITHUB_REF
      run: echo $GITHUB_REF
    - uses: ncipollo/release-action
      with: 
        myInput: 'testing 123'
