name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo GITHUB_REF
      run: echo $GITHUB_REF
    - uses: ncipollo/release-action@release/test
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
