name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo GITHUB_REF
      run: echo $GITHUB_REF
    - uses: ncipollo/release-action@release/1.5.0
      with:
        allowUpdates: true
        artifact: "images/*.png,text/*.txt"
        artifactContentType: "raw"
        body: "body.md"
        draft: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
