name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo GITHUB_REF
        run: echo $GITHUB_REF
      - name: Publish release
        uses: ncipollo/release-action@test
        with:
          allowUpdates: true
          artifacts: "images/*.png,text/*.txt"
          artifactContentType: "raw"
          bodyFile: "body.md"
          draft: false
          prerelease: false
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
