name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo GITHUB_REF
        run: echo $GITHUB_REF
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: images/*.png,text/*.txt
          artifactContentType: "raw"
          bodyFile: "body.md"
          discussionCategory: "Release"
          draft: true
          prerelease: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
