name: Tags

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: "tag"
    - uses: actions/checkout@v1
    - name: Echo GITHUB_REF
      run: echo $GITHUB_REF
