name: Releases

on:
  push:
    tags:
      - '*'
      - '*/*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
      - name: Tar text folder
        run: tar -czf text.tar.gz text
      - name: Publish release
        id: release
        uses: ncipollo/release-action@v1.11.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: images,images/*.png,text/*.txt,text.tar.gz
          artifactContentType: "raw"
          bodyFile: "body.md"
          discussionCategory: "Release"
          draft: false
          generateReleaseNotes: true
          prerelease: false
          replacesArtifacts: true
          omitDraftDuringUpdate: true
      - name: Dump Release Outputs
        env:
          RELEASE_OUTPUT: ${{ toJson(steps.release.outputs) }}
        run: echo "$RELEASE_OUTPUT"
