name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo GITHUB_REF
      run: echo $GITHUB_REF
    - uses: ncipollo/release-action@release/v1.1.0
      with:
        artifact: "images/*.png,text/*.txt"
        artifactContentType: "raw"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
