name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo GITHUB_REF
      run: echo $GITHUB_REF
    - uses: ncipollo/release-action@test
      with:
        allowUpdates: true
        artifacts: "images/*.png,text/*.txt"
        artifactContentType: "raw"
        bodyFile: "body.md"
        draft: true
        omitBody: true
        omitName: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
