name: Releases

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo GITHUB_REF
      run: echo $GITHUB_REF
    - uses: ncipollo/release-action@release/test
      with:
        artifact: "flawless.png"
        artifactContentType: "image/png"
        bodyFile: "body.md"
        commit: 'master'
        draft: "true"
        name: "the best release ever"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: '3.14.15'
